name: rick_morty_app
repository: https://github.com/teoboetti/rick_morty_app

ide:
  intellij:
    enabled: false

packages:
  - app
  - packages/**

command:
  version:
    # Only allow versioning to happen on master branch.
    branch: master
    # Generates a link to a prefilled GitHub release creation page.
    releaseUrl: true
    # Additionally build a changelog at the root of the workspace.
    workspaceChangelog: true

  bootstrap:
    environment:
      sdk: ">=3.3.0 <4.0.0"
      flutter: ">=3.19.2"
    
    dependencies:
      dio: ^5.4.1
      dio_cache_interceptor: ^3.5.0
      dio_cache_interceptor_hive_store: ^3.2.2
      hive: ^2.2.3

    dev_dependencies:
      build_runner: ^2.4.9
      mocktail: ^1.0.3

scripts:
  lint:all:
    run: melos run analyze && melos run format
    description: Run all static analysis checks.

  analyze:
    # We are setting the concurrency to 1 because a higher concurrency can crash
    # the analysis server on low performance machines (like GitHub Actions).
    run: |
      melos exec -c 1 -- \
        dart analyze . --fatal-infos
    description: |
      Run `dart analyze` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.

  format:
    run: |
      dart pub global run flutter_plugin_tools format && \
      swiftformat .
    description: |
      Formats the code of all packages (Java, Objective-C, and Dart).
       - Requires `flutter_plugin_tools` (`pub global activate flutter_plugin_tools`).
       - Requires `git`.
       - Requires `clang-format` (can be installed via Brew on MacOS).
       - Requires `swiftformat` (can be installed via Brew on macOS).

  localize:
    exec: |
      flutter gen-l10n
    description: 
      Generate localizations files
    packageFilters:
      fileExists: l10n.yaml
      dependsOn: flutter_gen
  
  test:select:
    run: melos exec -c 1 -- flutter test
    packageFilters:
      dirExists: test
    description: Run `flutter test` for selected packages.

  test:
    run: melos run test:select --no-select
    description: Run all Flutter tests in this project.

  generate:select:
    exec: |
      dart run build_runner build --delete-conflicting-outputs
    description: |
      Generate .g.dart files if the package for selected packages.
    packageFilters:
      dependsOn: build_runner

  generate:
    run: melos run generate:select --no-select
    description: Generate .g.dart files if the package depends on build_runner.