name: api
description: Api
version: 0.1.0
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: ">=3.19.2" 

dependencies: 
  dio: ^5.4.1
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
