name: rick_morty_app
description: Rick and Morty App
version: 1.0.0
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: ">=3.19.2"

dependencies:
  api: ^0.1.0
  bloc: ^8.1.3
  bloc_concurrency: ^0.2.5
  cached_network_image: ^3.3.1
  dio: ^5.4.1
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.7
  go_router: ^13.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.4.1
  intl: ^0.18.1
  stream_transform: ^2.1.0
  

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.4.1
  injectable_generator: ^2.6.1
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/Get-Schwifty.ttf
  fonts:
    - family: Schwifty
      fonts:
        - asset: assets/fonts/Get-Schwifty.ttf
